all: $(EXE)

XX=./xrns-export.sh

a.o: a.c
	$(CC) $(CFLAGS) -c a.c

song.xrns.inc.c: song.xrns
	$(XX) song.xrns > song.xrns.inc.c

dotd.o: dotd.c a.h song.xrns.inc.c
	$(CC) $(CFLAGS) -c dotd.c

$(EXE): dotd.o a.o
	$(CC) dotd.o a.o -o $(EXE) $(LINK)

clean:
	rm -rf *.o *.inc.c $(EXE)

